Import('RTT_ROOT')
Import('rtconfig')
Import('env')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

include = [cwd, cwd + '/include']
lib = ['rcbase64']
libpath  = [cwd]

env.StaticLibrary([cwd + '/rcbase64'], src)

group = DefineGroup('rcbase64', src, depend = [''], CPPPATH = include, LIBS = lib, LIBPATH = libpath)

Return('group')
