Import('RTT_ROOT')
Import('rtconfig')
Import('env')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

include = [cwd, cwd + '/include']
lib = []
libpath  = [cwd]

env.StaticLibrary([cwd + '/rchttp'], src)

group = DefineGroup('rchttp', src, depend = [''], CPPPATH = include, LIBS = lib, LIBPATH = libpath)

Return('group')
